apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todolist
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "todolist"
  PORT: "5000"
  NODE_ENV: "production"
